### ISSUE TITLE
Linux Compilation Failure: error: use of undeclared identifier 'L__FUNCTION__'

### ISSUE THREAD

**Issue by MattEqualsCoder** [Voulz/OutlinerShortcuts#7]
I'm getting a some errors when compiling on Linux. Upon doing some digging, I discovered that the issue is that this code in OutlinerShortcutsEditorDefinitions.h doesn't appear to be working as expected as a workaround for some of the Windows-based macros:

```
// ----------- For Mac where these are not available. To be tested -------------
#ifndef _CRT_WIDE_
#define _CRT_WIDE_(s) L ## s
#endif
#ifndef _CRT_WIDE
#define _CRT_WIDE(s) _CRT_WIDE_(s)
#endif
#ifndef __FILEW__
#define __FILEW__     _CRT_WIDE(__FILE__)
#endif
#ifndef __FUNCTIONW__
#define __FUNCTIONW__ _CRT_WIDE(__FUNCTION__)
#endif
// ---------------------------------------------------------------
```

While I'm assuming the intention here is to maybe make the __FILE__ and __FUNCTION__ a certain length or something along those lines, it just ends up trying to use a macro L__FUNCTION__, which does not exist.

For what it's worth, __FUNCTIONW__ and __FILEW__ do not appear to be on the current list of supported Microsoft Macros: https://learn.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170

I'm not sure if this means that they may fully deprecate it in the future or what, but it's something to consider.

To resolve, I just replaced the block with the following. It may not be as pretty of a log as you 
```
// ----------- For Mac where these are not available. To be tested -------------
#ifndef __FILEW__
#define __FILEW__     __FILE__
#endif
#ifndef __FUNCTIONW__
#define __FUNCTIONW__ __FUNCTION__
#endif
// ---------------------------------------------------------------
```

While this does function and at least allow it to run (which I'm happy enough with personally for now), it doesn't appear to be working exactly as expected:

```
LogOutlinerShortcutsEditor:  ==== [慍䍰浯慭摮s䤨摮硥㸠‽⤰☠⠠湉敤⁸‼牁慲乹浵)桓瑵潤湷潍畤敬⸀捓湥佥瑵楬敮䍲汯慬獰䅥汬畏汴湩牥s慦獬e佅瑵楬敮䕲灸湡楳湯敂慨楶牯湏慍佰数㩮䔺灸湡䅤汬⼀ 敄慦汵⁴摅瑩牯䈠桥癡潩⹲䔠灸湡獤愠汬琠敨愠瑣牯⁳湩琠敨匠散敮传瑵楬敮⹲
潃浭湥t摅瑩牯獕牥敓瑴湩獧漀数慲潴⡲)潃汬灡敳潔潒瑯吮潯呬灩䔀畏汴湩牥硅慰獮潩䉮桥癡潩佲䵮灡灏湥唀摮牥祬湩呧灹e敌敶䕬楤潴r捓湥佥瑵楬敮䍲汯慬獰䅥汬畏汴湩牥味副潯t硅慰摮汁⹬潃浭湥t潍畤敬敒慬楴敶慐桴䐀晥畡瑬畏汴湩牥硅慰獮潩䉮桥癡潩佲䵮灡灏湥䤀摮硥㰠䜠瑥慍䥸摮硥⤨䌀瑡来牯y匮散敮畏汴湩牥潃汬灡敳潔潒瑯⸀捓湥佥瑵楬敮䍲汯慬獰䅥汬畏汴湩牥味副潯t灁汰佹瑵楬敮䕲灸湡楳湯牆浯湏慍佰数敮卤瑥楴杮s潢敮匀慴瑲灵潍畤敬匀慴瑲湉敤⁸㴾〠☠…瑓牡䥴摮硥㰠‽牁慲⹹畎⡭)摁牤㰠䜠瑥慄慴⤨簠⁼摁牤㸠‽䜨瑥慄慴⤨⬠䄠牲祡慍⥸] ==== 
```

**Comment by Voulz** [comment]
Thanks for looking into this and coming back to me.
I do not have Linux or Mac so I am unable to test for those, but you gave some valuable information.

FYI, I found `__FUNCTIONW__` and `__FILEW__` in `C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt.h` which defines them exactly how I wrote it in the #ifndef areas.
The `_CRT_WIDE` ensures the text is stored as wide characters by using 16bits of storage instead of 8. If I just use the `__FUNCTION__` macro directly, it also outputs non english characters:
```LogOutlinerShortcutsEditor:  ==== [但瑵楬敮卲潨瑲畣獴摅瑩牯潍畤敬㨺瑓牡畴䵰摯汵e] ==== ```
I realised that this function can actually be replaced with the UE `TEXT` macro:
```cpp
#ifndef __FILEW__
#define __FILEW__     TEXT(__FILE__)
#endif
#ifndef __FUNCTIONW__
#define __FUNCTIONW__ TEXT(__FUNCTION__)
#endif
```

From what I read, it seems that `__FUNCTION__` cannot be expanded in the preprocessor in Linux:
https://stackoverflow.com/questions/4773941/wide-version-of-function-on-linux
https://stackoverflow.com/questions/55918730/widen-version-of-function-in-linux

It seems though that I found an easier solution, which is to use the `__FUNCTION__` macro instead of the `__FUNCTIONW__`, and wherever it is used in my calls to `UE_LOG`, to also replace the `%s` with `%hs`.
Example, replace line 51:
```cpp
#define __LOGH__(LogCategory, Format, ...) UE_LOG(LogCategory, Display, TEXT("[%s]  " Format), __FUNCTIONW__, ##__VA_ARGS__);
```
with:
```cpp
#define __LOGH__(LogCategory, Format, ...) UE_LOG(LogCategory, Display, TEXT("[%hs]  " Format), __FUNCTION__, ##__VA_ARGS__);
```
Could you let me know if that works on your end?

**Comment by MattEqualsCoder** [comment]
Sorry for the delay. I updated to use the bottom newer solution (%hs), and it does appear like it's working!

```
LogOutlinerShortcutsEditor:  ==== [StartupModule] ==== 
LogOutlinerShortcutsEditor:  ==== [RegisterSettings] ==== 
LogOutlinerShortcutsEditor: Display: [RegisterSettings]  Settings Registered
LogOutlinerShortcutsEditor:  ==== [MapCommands] ==== 
```

I did notice there's also the __FILEW__ and I made similar updates to where it defines _FILENAME__ and the WHERE definition, but it does not appear that WHERE is used in this as far as I can tell.

**Comment by Voulz** [comment]
@MattEqualsCoder , could you check if this pull request #9  would fix the issue?
https://github.com/Voulz/OutlinerShortcuts/tree/v1.1.2

**Comment by MattEqualsCoder** [comment]
Pulled in the code and gave it a test run. Seems to work for me! Thanks for this!
